services:
    resources-service:
        build: ./resource-service
        ports:
            - "8080:8080"
        environment:
            SPRING_DATASOURCE_URL: jdbc:postgresql://resource-db:5432/resource-db
            SPRING_DATASOURCE_USERNAME: postgres
            SPRING_DATASOURCE_PASSWORD: postgres
            SPRING_JPA_HIBERNATE_DDL_AUTO: update
            SERVER_PORT: 8080
            SONG_SERVICE_NAME: song-service
            SONG_SERVICE_PORT: 8081
        depends_on:
            - resource-db
        networks:
            - app-network

    resource-db:
        image: postgres:latest
        environment:
            POSTGRES_DB: resource-db
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - "5433:5432"
        volumes:
            - resources_data:/var/lib/postgresql/data
        networks:
            - app-network

    song-service:
        build: ./song-service
        ports:
            - "8081:8081"
        environment:
            SPRING_DATASOURCE_URL: jdbc:postgresql://song-db:5432/song-db
            SPRING_DATASOURCE_USERNAME: postgres
            SPRING_DATASOURCE_PASSWORD: postgres
            SPRING_JPA_HIBERNATE_DDL_AUTO: update
            SERVER_PORT: 8081
        depends_on:
            - song-db
        networks:
            - app-network

    song-db:
        image: postgres:latest
        environment:
            POSTGRES_DB: song-db
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - "5434:5432"
        volumes:
            - songs_data:/var/lib/postgresql/data
        networks:
            - app-network

volumes:
    resources_data:
    songs_data:

networks:
    app-network: